# Generated by Django 5.0.6 on 2024-05-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('title', models.CharField(blank=True, default='', max_length=254, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
                ('phone', models.CharField(blank=True, default='', max_length=254, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, default='', max_length=254, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'About Me Section',
                'verbose_name_plural': 'About Me Sections',
                'ordering': ('title',),
            },
        ),
    ]
