# Generated by Django 5.0.6 on 2024-05-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aboutmesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'About Me Section',
                'verbose_name_plural': 'About Me Sections',
                'ordering': ('title',),
            },
        ),
        migrations.DeleteModel(
            name='AboutMeSection',
        ),
    ]
