# Generated by Django 5.0.6 on 2024-05-19 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aboutme_delete_aboutmesection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutMe',
        ),
    ]
